# Generated by Django 3.1.5 on 2021-01-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_controller', '0002_addresslist_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresslist',
            old_name='default',
            new_name='is_default',
        ),
    ]
